In [1]:
import pandas as pd
import numpy as np

x_train = pd.read_csv("X_train")

In [2]:
x_train

age  fnlwgt  sex  capital_gain  capital_loss  hours_per_week  \
0       39   77516    1          2174             0              40   
1       50   83311    1             0             0              13   
2       38  215646    1             0             0              40   
3       53  234721    1             0             0              40   
4       28  338409    0             0             0              40   
5       37  284582    0             0             0              40   
6       49  160187    0             0             0              16   
7       52  209642    1             0             0              45   
8       31   45781    0         14084             0              50   
9       42  159449    1          5178             0              40   
10      37  280464    1             0             0              80   
11      30  141297    1             0             0              40   
12      23  122272    0             0             0              30   
13      32  205019    1             0             0              50   
14      40  121772    1             0             0              40   
15      34  245487    1             0             0              45   
16      25  176756    1             0             0              35   
17      32  186824    1             0             0              40   
18      38   28887    1             0             0              50   
19      43  292175    0             0             0              45   
20      40  193524    1             0             0              60   
21      54  302146    0             0             0              20   
22      35   76845    1             0             0              40   
23      43  117037    1             0          2042              40   
24      59  109015    0             0             0              40   
25      56  216851    1             0             0              40   
26      19  168294    1             0             0              40   
27      54  180211    1             0             0              60   
28      39  367260    1             0             0              80   
29      49  193366    1             0             0              40   
...    ...     ...  ...           ...           ...             ...   
32531   30   33811    0             0             0              99   
32532   34  204461    1             0             0              60   
32533   54  337992    1             0             0              50   
32534   37  179137    0             0             0              39   
32535   22  325033    1             0             0              35   
32536   34  160216    0             0             0              55   
32537   30  345898    1             0             0              46   
32538   38  139180    0         15020             0              45   
32539   71  287372    1             0             0              10   
32540   45  252208    0             0             0              40   
32541   41  202822    0             0             0              32   
32542   72  129912    1             0             0              25   
32543   45  119199    0             0             0              48   
32544   31  199655    0             0             0              30   
32545   39  111499    0             0             0              20   
32546   37  198216    0             0             0              40   
32547   43  260761    1             0             0              40   
32548   65   99359    1          1086             0              60   
32549   43  255835    0             0             0              40   
32550   43   27242    1             0             0              50   
32551   32   34066    1             0             0              40   
32552   43   84661    1             0             0              45   
32553   32  116138    1             0             0              11   
32554   53  321865    1             0             0              40   
32555   22  310152    1        

In [3]:
rows = np.array(x_train, dtype=float)

In [4]:
rows

array([[3.90000e+01, 7.75160e+04, 1.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [5.00000e+01, 8.33110e+04, 1.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [3.80000e+01, 2.15646e+05, 1.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       ...,
       [5.80000e+01, 1.51910e+05, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [2.20000e+01, 2.01490e+05, 1.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [5.20000e+01, 2.87927e+05, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00]])

In [5]:
mean = np.mean(rows, axis=0).reshape(1,-1)

In [6]:
mean

array([[3.85816468e+01, 1.89778367e+05, 6.69205491e-01, 1.07764884e+03,
        8.73038297e+01, 4.04374559e+01, 2.94831240e-02, 6.42793526e-02,
        2.14981112e-04, 6.97030189e-01, 3.42741316e-02, 7.80381438e-02,
        3.98636406e-02, 4.29962225e-04, 5.63864746e-02, 2.86539111e-02,
        3.60861153e-02, 1.32981174e-02, 5.15954670e-03, 1.02269586e-02,
        1.98396855e-02, 1.57857560e-02, 3.27692638e-02, 4.24434139e-02,
        1.64460551e-01, 1.26838856e-02, 3.22502380e-01, 5.29160652e-02,
        1.56629096e-03, 1.76898744e-02, 2.23918184e-01, 1.36451583e-01,
        7.06366512e-04, 4.59936734e-01, 1.28374436e-02, 3.28091889e-01,
        3.14793772e-02, 3.04966064e-02, 1.15782685e-01, 2.76404287e-04,
        1.25886797e-01, 1.24873315e-01, 3.05273180e-02, 4.20748749e-02,
        6.14845981e-02, 1.01194681e-01, 4.57602653e-03, 1.27145972e-01,
        1.99318203e-02, 1.12097294e-01, 2.85003532e-02, 4.90464052e-02,
        5.66014557e-02, 4.05177974e-01, 2.55059734e-01, 3.012806

In [7]:
std = np.std(rows, axis=0).reshape(1,-1)

In [8]:
std

array([[1.36402231e+01, 1.05548357e+05, 4.70499205e-01, 7.38517868e+03,
        4.02954031e+02, 1.23472391e+01, 1.69156346e-01, 2.45249908e-01,
        1.46606581e-02, 4.59542277e-01, 1.81932448e-01, 2.68231601e-01,
        1.95638776e-01, 2.07310723e-02, 2.30666513e-01, 1.66831845e-01,
        1.86504444e-01, 1.14548145e-01, 7.16444399e-02, 1.00609979e-01,
        1.39449175e-01, 1.24645762e-01, 1.78032130e-01, 2.01598538e-01,
        3.70692970e-01, 1.11906232e-01, 4.67434054e-01, 2.23865931e-01,
        3.95453878e-02, 1.31821632e-01, 4.16867882e-01, 3.43267459e-01,
        2.65681681e-02, 4.98392350e-01, 1.12572837e-01, 4.69518478e-01,
        1.74609353e-01, 1.71949305e-01, 3.19964146e-01, 1.66231131e-02,
        3.31721738e-01, 3.30575211e-01, 1.72033139e-01, 2.00760005e-01,
        2.40217073e-01, 3.01586335e-01, 6.74913810e-02, 3.33136419e-01,
        1.39766029e-01, 3.15486118e-01, 1.66397365e-01, 2.15964940e-01,
        2.31079491e-01, 4.90926454e-01, 4.35894788e-01, 1.709396

In [9]:
theta = np.ones((rows.shape[1]+1,1),dtype = float) # sigmoid function?

In [10]:
theta.shape

(107, 1)

In [11]:
for i in range(rows.shape[0]):
    rows[i,:] = (rows[i,:] - mean) / std

In [12]:
rows

array([[ 0.03067056, -1.06361075,  0.70307135, ..., -0.04540836,
        -0.02217266, -0.13502327],
       [ 0.83710898, -1.008707  ,  0.70307135, ..., -0.04540836,
        -0.02217266, -0.13502327],
       [-0.04264203,  0.2450785 ,  0.70307135, ..., -0.04540836,
        -0.02217266, -0.13502327],
       ...,
       [ 1.42360965, -0.35877741, -1.42233076, ..., -0.04540836,
        -0.02217266, -0.13502327],
       [-1.21564337,  0.11095988,  0.70307135, ..., -0.04540836,
        -0.02217266, -0.13502327],
       [ 0.98373415,  0.92989258, -1.42233076, ..., -0.04540836,
        -0.02217266, -0.13502327]])

In [13]:
data_x_train = rows # store x train data

In [14]:
y_train = pd.read_csv("Y_train", header=None) # matching classification of X_train data (1 means >50K, 0 means otherwise)

In [15]:
y_train

0
0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      1
8      1
9      1
10     1
11     1
12     0
13     0
14     1
15     0
16     0
17     0
18     0
19     1
20     1
21     0
22     0
23     0
24     0
25     1
26     0
27     1
28     0
29     0
...   ..
32531  0
32532  1
32533  1
32534  0
32535  0
32536  1
32537  0
32538  1
32539  1
32540  0
32541  0
32542  0
32543  0
32544  0
32545  1
32546  0
32547  0
32548  0
32549  0
32550  0
32551  0
32552  0
32553  0
32554  1
32555  0
32556  0
32557  1
32558  0
32559  0
32560  1

[32561 rows x 1 columns]

In [16]:
data_y_train = np.array(y_train, dtype=float)

In [17]:
data_y_train # store y train data

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [1.]])

In [18]:
# count items of class 0 and class 1
class_0_id = []
class_1_id = []
for i in range(data_y_train.shape[0]):
    if data_y_train[i][0] == 0:
        class_0_id.append(i)
    else:
        class_1_id.append(i)

In [19]:
class_0 = data_x_train[class_0_id] # train items of class 0
class_1 = data_x_train[class_1_id] # train items of class 1

In [20]:
mean_0 = np.mean(class_0, axis=0) # mean/mu of class 0
mean_1 = np.mean(class_1, axis=0) # mean/mu of class 1

In [21]:
# calculating covarient/sigma of features
n = class_0.shape[1]
cov_0 = np.zeros((n,n))
cov_1 = np.zeros((n,n))

for i in range(class_0.shape[0]):
    cov_0 += np.dot(np.transpose([class_0[i] - mean_0]), [(class_0[i] - mean_0)]) / class_0.shape[0]

for i in range(class_1.shape[0]):
    cov_1 += np.dot(np.transpose([class_1[i] - mean_1]), [(class_1[i] - mean_1)]) / class_1.shape[0]

cov = (cov_0*class_0.shape[0] + cov_1*class_1.shape[0]) / (class_0.shape[0] + class_1.shape[0])



In [22]:
# find the best function: y_star = wx + b
from numpy.linalg import inv

best_w = np.transpose(((mean_0 - mean_1)).dot(inv(cov)))
best_b = (-0.5)*(mean_0).dot(inv(cov)).dot(mean_0) + 0.5*(mean_1).dot(inv(cov)).dot(mean_1) + np.log(float(class_0.shape[0])/class_1.shape[0])



In [23]:
best_b

1.9700737654821208

In [24]:
best_w.shape

(106,)

In [25]:
# with the best b, w, calculate probabilities
# step inside func(self,x)

arr = np.empty([data_x_train.shape[0],1],dtype=float)
for i in range(data_x_train.shape[0]):
    z = data_x_train[i,:].dot(best_w) + best_b
    z *= (-1)
    arr[i][0] = 1 / (1+np.exp(z))

In [26]:
result = np.clip(arr, 1e-8, 1-(1e-8)) # remove the extremely small?

In [27]:
result

array([[0.93521642],
       [0.46891063],
       [0.9845273 ],
       ...,
       [0.9704869 ],
       [0.98773459],
       [0.10078863]])

In [28]:
# put results to class 0 or 1
ans = np.ones([result.shape[0],1],dtype=int)
for i in range(result.shape[0]):
    if result[i] > 0.5:
        ans[i] = 0;

In [29]:
# compare the ans to Y_train; examine the rate of correct prediction
yes_count = 0
for i in range(data_y_train.shape[0]):
    if (data_y_train[i][0]==ans[i]):
        yes_count += 1
        
print("Correct prediction at ", yes_count/data_y_train.shape[0])

Correct prediction at  0.8422652866926691


In [31]:
# attempt to predict from X_test

# process X_test data
x_test = pd.read_csv("X_test")
rows = np.array(x_train, dtype=float)
for i in range(rows.shape[0]):
    rows[i,:] = (rows[i,:] - mean) / std
data_x_test = rows

In [32]:
# step into func(self,x) to calculate probabilities
arr = np.empty([data_x_test.shape[0],1],dtype=float)
for i in range(data_x_test.shape[0]):
    z = data_x_test[i,:].dot(best_w) + best_b
    z *= (-1)
    arr[i][0] = 1 / (1+np.exp(z))
result = np.clip(arr, 1e-8, 1-(1e-8))

In [33]:
# put results to class 0 or 1
ans = np.ones([result.shape[0],1],dtype=int)
for i in range(result.shape[0]):
    if result[i] > 0.5:
        ans[i] = 0;

In [34]:
ans.shape

(32561, 1)

In [54]:
# output results to a file
# an 'id' column and a 'label' column
ansid = np.arange(ans.shape[0])

In [55]:
ansid

array([    0,     1,     2, ..., 32558, 32559, 32560])

In [56]:
label = ans.flatten()

In [57]:
label

array([0, 1, 0, ..., 0, 0, 1])

In [58]:
dict = {'id': ansid, 'label': label }

In [60]:
df = pd.DataFrame(dict)


In [61]:
df

id  label
0          0      0
1          1      1
2          2      0
3          3      0
4          4      1
5          5      1
6          6      0
7          7      0
8          8      0
9          9      1
10        10      1
11        11      0
12        12      0
13        13      0
14        14      0
15        15      0
16        16      0
17        17      0
18        18      0
19        19      0
20        20      1
21        21      0
22        22      0
23        23      0
24        24      0
25        25      1
26        26      0
27        27      0
28        28      0
29        29      0
...      ...    ...
32531  32531      0
32532  32532      1
32533  32533      1
32534  32534      0
32535  32535      0
32536  32536      0
32537  32537      0
32538  32538      0
32539  32539      1
32540  32540      0
32541  32541      0
32542  32542      0
32543  32543      0
32544  32544      0
32545  32545      0
32546  32546      0
32547  32547      0
32548  32548      1
32549  32549      0
32550  32550      0
32551  32551      0
32552  32552      0
32553  32553      0
32554  32554      1
32555  32555      0
32556  32556      1
32557  32557      0
32558  32558      0
32559  32559      0
32560  32560      1

[32561 rows x 2 columns]

In [62]:
df.to_csv('submission.csv')