# This is based on the sample code provided by TA2019
# at https://ntumlta2019.github.io/ml-web-hw2/LogisticRegression.html

In [1]:
# get the training data
import numpy as np
import pandas as pd

X_train = np.genfromtxt('X_train', delimiter=',', skip_header=1)
# X_train = np.array(pd.read_csv("X_train"), dtype=float)

In [2]:
X_train.shape

(32561, 106)

In [3]:
Y_train = np.genfromtxt('Y_train', delimiter=',')
# Y_train = np.array(pd.read_csv("Y_train", header=None), dtype=float)

In [4]:
Y_train.shape

(32561,)

In [5]:
# normalize data
# 0 age, 1 fnlwgt, 3 capital_gain, 4 capital_loss, 5 hours_per_week

# col = [0,1,3,4,5,7,10,12,25,26,27,28] # this line by TA does not make sense
col = [0,1,3,4,5]

In [6]:
# into _normalize_column_normal
length = len(col)
X_mean = np.reshape(np.mean(X_train[:,col],0), (1, length))

In [7]:
X_mean

array([[3.85816468e+01, 1.89778367e+05, 1.07764884e+03, 8.73038297e+01,
        4.04374559e+01]])

In [8]:
X_std = np.reshape(np.std(X_train[:,col],0), (1, length))

In [9]:
X_std

array([[1.36402231e+01, 1.05548357e+05, 7.38517868e+03, 4.02954031e+02,
        1.23472391e+01]])

In [10]:
X_train[:,col] = np.divide(np.subtract(X_train[:,col],X_mean), X_std)

In [11]:
X_train

array([[ 0.03067056, -1.06361075,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.83710898, -1.008707  ,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.04264203,  0.2450785 ,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 1.42360965, -0.35877741,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-1.21564337,  0.11095988,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.98373415,  0.92989258,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [12]:
# end of X_train normalization
# this makes age, fnlwgt, capital_gain, capital_loss, hours_per_week data into normal distribution

In [13]:
# step into the train(X_train, Y_train) function

# first, split a validation set
dev_size = 0.1155
train_len = int(round(len(X_train)*(1-dev_size)))

In [14]:
train_len

28800

In [15]:
X_train_data = X_train[0:train_len] # use a different variable name to maintain source data

In [16]:
X_train_data.shape

(28800, 106)

In [17]:
Y_train_data = Y_train[0:train_len]

In [18]:
Y_train_data.shape

(28800,)

In [19]:
X_dev = X_train[train_len:None]
Y_dev = Y_train[train_len:None]

In [20]:
X_dev.shape

(3761, 106)

In [21]:
# X_train_data and Y_train data are training set

# step 2, use 0+0*x1+0*x2+... for weight initialization
w = np.zeros((X_train_data.shape[1],))
b = np.zeros((1,))

In [22]:
regularize = True
lamda = 0.001
max_iter = 1
batch_size = 32
learning_rate = 0.2

In [23]:
num_train = len(Y_train_data)
num_dev = len(Y_dev)
step = 1

In [24]:
loss_train = []
loss_validation = []
train_acc = []
dev_acc = []

In [25]:
# into the training epochs
for epoch in range(max_iter):
    # random shuffle for each epoch
    # into the _shuffle(,)
    randomize = np.arange(len(X_train_data))
    np.random.shuffle(randomize)
    X_train_data = X_train_data[randomize]
    Y_train_data = Y_train_data[randomize]
    print(X_train_data.shape)
    print(Y_train_data.shape)
    # more to come... not complete yet

(28800, 106)
(28800,)
