In [1]:
import pandas as pd
import numpy as np

testdata = pd.read_csv("given/test_X.csv")
pm2_5_test = testdata[testdata['AMB_TEMP']=='PM2.5'].iloc[:,2:]

In [2]:
x_test = np.array(pm2_5_test)
x_test

array([['27', '13', '24', ..., '29', '27', '28'],
       ['46', '47', '57', ..., '59', '61', '61'],
       ['10', '10', '25', ..., '36', '25', '22'],
       ...,
       ['16', '25', '12', ..., '11', '3', '0'],
       ['29', '27', '23', ..., '35', '35', '26'],
       ['12', '8', '7', ..., '0', '0', '0']], dtype=object)

In [3]:
x_test.shape

(240, 9)

In [4]:
alldata = pd.read_csv("original_data.csv")

In [5]:
alldata = alldata.replace(['NR'], [0.0])
alldata = alldata.replace([''],[0.0])
alldata

日期  測站          測項    00    01    02    03    04    05    06  \
0     2014/01/01  豐原    AMB_TEMP    14    14    14    13    12    12    12   
1     2014/01/01  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   
2     2014/01/01  豐原          CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37   
3     2014/01/01  豐原        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1   
4     2014/01/01  豐原          NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9   
5     2014/01/01  豐原         NO2    16   9.2   8.2   6.9   6.8   3.8   6.9   
6     2014/01/01  豐原         NOx    17   9.8   8.7   8.6   8.5   5.3   8.8   
7     2014/01/01  豐原          O3    16    30    27    23    24    28    24   
8     2014/01/01  豐原        PM10    56    50    48    35    25    12     4   
9     2014/01/01  豐原       PM2.5    26    39    36    35    31    28    25   
10    2014/01/01  豐原    RAINFALL     0     0     0     0     0     0     0   
11    2014/01/01  豐原          RH    77    68    67    74    72    73    74   
12    2014/01/01  豐原         SO2   1.8     2   1.7   1.6   1.9   1.4   1.5   
13    2014/01/01  豐原         THC     2     2     2   1.9   1.9   1.8   1.9   
14    2014/01/01  豐原       WD_HR    37    80    57    76   110   106   101   
15    2014/01/01  豐原  WIND_DIREC    35    79   2.4    55    94   116   106   
16    2014/01/01  豐原  WIND_SPEED   1.4   1.8     1   0.6   1.7   2.5   2.5   
17    2014/01/01  豐原       WS_HR   0.5   0.9   0.6   0.3   0.6   1.9     2   
18    2014/01/02  豐原    AMB_TEMP    16    15    15    14    14    15    16   
19    2014/01/02  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   
20    2014/01/02  豐原          CO  0.26  0.25  0.28  0.27  0.24  0.26  0.34   
21    2014/01/02  豐原        NMHC  0.06  0.05  0.06  0.05  0.05  0.07  0.09   
22    2014/01/02  豐原          NO   1.4   1.1   1.3     1   1.2   1.1   1.6   
23    2014/01/02  豐原         NO2   3.7   3.2   3.3   3.1   3.1   4.3   9.4   
24    2014/01/02  豐原         NOx     5   4.3   4.7   4.1   4.3   5.5    11   
25    2014/01/02  豐原          O3    39    38    39    39    34    31    30   
26    2014/01/02  豐原        PM10    49    34    31    16    18     8    16   
27    2014/01/02  豐原       PM2.5    21    23    30    30    22    18    13   
28    2014/01/02  豐原    RAINFALL     0     0     0     0     0     0     0   
29    2014/01/02  豐原          RH    65    66    70    71    70    67    59   
...          ...  ..         ...   ...   ...   ...   ...   ...   ...   ...   
6540  2014/12/30  豐原         NOx    10   6.7     6   5.8     5   5.3   9.1   
6541  2014/12/30  豐原          O3    12    13    16    22    17    14    12   
6542  2014/12/30  豐原        PM10    27    14    13    26    27    25     5   
6543  2014/12/30  豐原       PM2.5    25    12     8     7    11    11     3   
6544  2014/12/30  豐原    RAINFALL     0     0     0     0     0     0     0   
6545  2014/12/30  豐原          RH    84    85    86    84    83    80    77   
6546  2014/12/30  豐原         SO2   1.4   1.1   1.3   1.4   1.3   1.1   1.4   
6547  2014/12/30  豐原         THC   1.9   1.8   1.8   1.8   1.8   1.7   1.8   
6548  2014/12/30  豐原       WD_HR   129   105   105   110    99   101   104   
6549  2014/12/30  豐原  WIND_DIREC    91   108   107   103    89    85   104   
6550  2014/12/30  豐原  WIND_SPEED   1.1   1.4   1.7   1.9   1.7   1.6   1.4   
6551  2014/12/30  豐原       WS_HR   0.7   1.4   1.7   1.6   1.8   1.8   1.6   
6552  2014/12/31  豐原    AMB_TEMP    13    12    11    11    11    11    10   
6553  2014/12/31  豐原         CH4   1.8   1.8   1.7   1.7   1.7   1.7   1.7   
6554  2014/12/31  豐原          CO  0.36   0.3  0.26  0.24  0.18   0.2  0.25   
6555  2014/12/31  豐原        NMHC  0.12  0.12  0.07  0.06  0.05  0.06  0.07   
6556  2014/12/31  豐原          NO   1.4   1.3   1.1   0.9   1.1   1.2   1.5   
6557  2014/12/31  豐原         NO2   9.3   7.5   5.2   3.9   3.5   4.5   6.4   
6558  2014/12/31  豐原         NOx    11   8.8   6.2   4.9   4.7   5.7   7.8   
6559  2014/12/31  豐原          O3    

In [6]:
pm2_5_all = np.array(alldata[alldata['測項']=='PM2.5'].iloc[:,3:])

In [7]:
pm2_5_all

array([['26', '39', '36', ..., '30', '24', '13'],
       ['21', '23', '30', ..., '19', '22', '26'],
       ['19', '25', '27', ..., '29', '23', '37'],
       ...,
       ['14', '22', '30', ..., '21', '21', '16'],
       ['25', '12', '8', ..., '27', '24', '10'],
       ['10', '3', '8', ..., '28', '25', '28']], dtype=object)

In [8]:
pm2_5_all[0]

array(['26', '39', '36', '35', '31', '28', '25', '20', '19', '30', '41',
       '44', '33', '37', '36', '45', '42', '49', '45', '44', '41', '30',
       '24', '13'], dtype=object)

In [36]:
d = np.zeros((240,3))

for i in range (240):
    a = x_test[i,:]
    f = 0
    for j in range (365):
        for k in range (24-9):
            b = pm2_5_all[j,k:k+9]
            if np.array_equal(a,b) :
                print(i, ": ", j, "-", k)
                d[i,0] = j
                d[i,1] = k
                f = 1
                break
        if (f == 1):
            break


1 :  20 - 6
2 :  23 - 7
3 :  28 - 13
6 :  28 - 9
8 :  20 - 9
9 :  21 - 6
10 :  27 - 12
11 :  29 - 5
12 :  29 - 13
13 :  29 - 0
16 :  28 - 6
18 :  24 - 0
19 :  21 - 0
20 :  57 - 1
21 :  52 - 4
22 :  58 - 7
24 :  55 - 10
25 :  54 - 1
26 :  56 - 12
28 :  52 - 6
29 :  54 - 0
35 :  55 - 6
37 :  53 - 10
39 :  55 - 4
40 :  88 - 8
41 :  87 - 3
42 :  81 - 2
45 :  82 - 6
47 :  87 - 1
48 :  82 - 0
49 :  88 - 5
54 :  85 - 10
56 :  81 - 14
59 :  81 - 7
66 :  114 - 11
69 :  118 - 11
70 :  115 - 0
71 :  114 - 3
74 :  116 - 13
75 :  119 - 13
76 :  114 - 0
78 :  115 - 5
79 :  113 - 3
81 :  147 - 0
83 :  150 - 5
87 :  149 - 9
88 :  147 - 14
91 :  142 - 5
92 :  145 - 14
93 :  144 - 2
94 :  146 - 13
96 :  144 - 9
97 :  141 - 9
99 :  146 - 4
100 :  176 - 13
101 :  174 - 7
102 :  171 - 12
106 :  173 - 12
108 :  174 - 6
112 :  176 - 5
113 :  172 - 14
115 :  176 - 4
117 :  175 - 4
118 :  178 - 9
122 :  205 - 14
124 :  205 - 9
128 :  201 - 0
130 :  203 - 2
132 :  208 - 14
133 :  202 - 11
134 :  210 - 2
135 :  

In [37]:
d

array([[  0.,   0.,   0.],
       [ 20.,   6.,   0.],
       [ 23.,   7.,   0.],
       [ 28.,  13.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.],
       [ 28.,   9.,   0.],
       [  0.,   0.,   0.],
       [ 20.,   9.,   0.],
       [ 21.,   6.,   0.],
       [ 27.,  12.,   0.],
       [ 29.,   5.,   0.],
       [ 29.,  13.,   0.],
       [ 29.,   0.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.],
       [ 28.,   6.,   0.],
       [  0.,   0.,   0.],
       [ 24.,   0.,   0.],
       [ 21.,   0.,   0.],
       [ 57.,   1.,   0.],
       [ 52.,   4.,   0.],
       [ 58.,   7.,   0.],
       [  0.,   0.,   0.],
       [ 55.,  10.,   0.],
       [ 54.,   1.,   0.],
       [ 56.,  12.,   0.],
       [  0.,   0.,   0.],
       [ 52.,   6.,   0.],
       [ 54.,   0.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.],
       [ 55.,   6.,   0.],
       [  0.,   0.,   0.],
 

In [28]:
d[0,0]

0.0

In [32]:
d[1,0]>0

True

In [40]:
for i in range (240):
    if d[i,0]>0:
        ii = int(d[i,0]*18+9)
        l = int(d[i,1])
        d[i,2] = alldata.iloc[ii,l+10] # this is the answer
        print(i, ") PM2.5 on ", alldata.iloc[ii,0], " at hour ", l+10, " is ", int(d[i,2]))

1 ) PM2.5 on  2014/01/21  at hour  16  is  61
2 ) PM2.5 on  2014/01/24  at hour  17  is  25
3 ) PM2.5 on  2014/01/29  at hour  23  is  34
6 ) PM2.5 on  2014/01/29  at hour  19  is  41
8 ) PM2.5 on  2014/01/21  at hour  19  is  49
9 ) PM2.5 on  2014/01/22  at hour  16  is  22
10 ) PM2.5 on  2014/01/28  at hour  22  is  40
11 ) PM2.5 on  2014/01/30  at hour  15  is  60
12 ) PM2.5 on  2014/01/30  at hour  23  is  54
13 ) PM2.5 on  2014/01/30  at hour  10  is  24
16 ) PM2.5 on  2014/01/29  at hour  16  is  71
18 ) PM2.5 on  2014/01/25  at hour  10  is  16
19 ) PM2.5 on  2014/01/22  at hour  10  is  13
20 ) PM2.5 on  2014/02/27  at hour  11  is  15
21 ) PM2.5 on  2014/02/22  at hour  14  is  29
22 ) PM2.5 on  2014/02/28  at hour  17  is  34
24 ) PM2.5 on  2014/02/25  at hour  20  is  55
25 ) PM2.5 on  2014/02/24  at hour  11  is  36
26 ) PM2.5 on  2014/02/26  at hour  22  is  30
28 ) PM2.5 on  2014/02/22  at hour  16  is  31
29 ) PM2.5 on  2014/02/24  at hour  10  is  31
35 ) PM2.5 on  2014

In [41]:
d

array([[  0.,   0.,   0.],
       [ 20.,   6.,  61.],
       [ 23.,   7.,  25.],
       [ 28.,  13.,  34.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.],
       [ 28.,   9.,  41.],
       [  0.,   0.,   0.],
       [ 20.,   9.,  49.],
       [ 21.,   6.,  22.],
       [ 27.,  12.,  40.],
       [ 29.,   5.,  60.],
       [ 29.,  13.,  54.],
       [ 29.,   0.,  24.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.],
       [ 28.,   6.,  71.],
       [  0.,   0.,   0.],
       [ 24.,   0.,  16.],
       [ 21.,   0.,  13.],
       [ 57.,   1.,  15.],
       [ 52.,   4.,  29.],
       [ 58.,   7.,  34.],
       [  0.,   0.,   0.],
       [ 55.,  10.,  55.],
       [ 54.,   1.,  36.],
       [ 56.,  12.,  30.],
       [  0.,   0.,   0.],
       [ 52.,   6.,  31.],
       [ 54.,   0.,  31.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.],
       [ 55.,   6.,  54.],
       [  0.,   0.,   0.],
 

In [42]:
d[:2]

array([[ 0.,  0.,  0.],
       [20.,  6., 61.]])

In [43]:
d[:,2]

array([  0.,  61.,  25.,  34.,   0.,   0.,  41.,   0.,  49.,  22.,  40.,
        60.,  54.,  24.,   0.,   0.,  71.,   0.,  16.,  13.,  15.,  29.,
        34.,   0.,  55.,  36.,  30.,   0.,  31.,  31.,   0.,   0.,   0.,
         0.,   0.,  54.,   0.,  37.,   0.,  57.,  41.,  37.,  46.,   0.,
         0.,  62.,   0.,  45.,  39.,  32.,   0.,   0.,   0.,   0.,  37.,
         0.,  23.,   0.,   0.,  43.,   0.,   0.,   0.,   0.,   0.,   0.,
        41.,   0.,   0.,  51.,  69.,  64.,   0.,   0.,  10.,  32.,  57.,
         0.,  59.,  43.,   0.,  20.,   0.,  48.,   0.,   0.,   0.,   9.,
        23.,   0.,   0.,   5.,  18.,  14.,  32.,   0.,  11.,   5.,   0.,
        11.,  12.,  20.,   9.,   0.,   0.,   0.,  26.,   0.,  33.,   0.,
         0.,   0.,  14.,  22.,   0.,  16.,   0.,  33.,  25.,   0.,   0.,
         0.,  13.,   0.,   1.,   0.,   0.,   0.,  18.,   0.,   2.,   0.,
        23.,  62.,  20.,  16.,   0.,  27.,  71.,  80.,  32.,   0.,   0.,
         0.,   0.,   0.,  20.,   0.,  14.,  12.,  3

In [44]:
y_pre = pd.read_csv('given/sampleSubmission.csv')

In [45]:
y_pre.value = d[:,2]

In [46]:
y_pre

id  value
0      id_0    0.0
1      id_1   61.0
2      id_2   25.0
3      id_3   34.0
4      id_4    0.0
5      id_5    0.0
6      id_6   41.0
7      id_7    0.0
8      id_8   49.0
9      id_9   22.0
10    id_10   40.0
11    id_11   60.0
12    id_12   54.0
13    id_13   24.0
14    id_14    0.0
15    id_15    0.0
16    id_16   71.0
17    id_17    0.0
18    id_18   16.0
19    id_19   13.0
20    id_20   15.0
21    id_21   29.0
22    id_22   34.0
23    id_23    0.0
24    id_24   55.0
25    id_25   36.0
26    id_26   30.0
27    id_27    0.0
28    id_28   31.0
29    id_29   31.0
..      ...    ...
210  id_210   30.0
211  id_211   79.0
212  id_212    0.0
213  id_213    0.0
214  id_214   35.0
215  id_215    0.0
216  id_216   66.0
217  id_217   62.0
218  id_218    0.0
219  id_219    0.0
220  id_220   40.0
221  id_221   74.0
222  id_222    0.0
223  id_223    0.0
224  id_224    0.0
225  id_225    0.0
226  id_226    0.0
227  id_227   56.0
228  id_228   27.0
229  id_229    0.0
230  id_230   39.0
231  id_231   11.0
232  id_232   11.0
233  id_233    0.0
234  id_234    0.0
235  id_235   14.0
236  id_236    0.0
237  id_237    0.0
238  id_238    0.0
239  id_239    0.0

[240 rows x 2 columns]

In [47]:
#y_pre.to_csv('given/test_ans_incomplete.csv')