In [10]:
f = open('train_updated.csv')
f.readline()

data01 = []
temp = f.readline().split(',')
data01.append(temp)
print(data01)

[['2014/1/1', '豐原', 'AMB_TEMP', '14', '14', '14', '13', '12', '12', '12', '12', '15', '17', '20', '22', '22', '22', '22', '22', '21', '19', '17', '16', '15', '15', '15', '15\n']]


In [12]:
data01 = []

with open('train_updated.csv') as f:
    count = 0
    for line in f:
        if 1 == count%18 :
            temp = line.split(',')
            data01.append(temp)
        count=count+1

print(data01);

[['2014/1/1', '豐原', 'AMB_TEMP', '14', '14', '14', '13', '12', '12', '12', '12', '15', '17', '20', '22', '22', '22', '22', '22', '21', '19', '17', '16', '15', '15', '15', '15\n'], ['2014/1/2', '豐原', 'AMB_TEMP', '16', '15', '15', '14', '14', '15', '16', '16', '17', '20', '22', '23', '24', '24', '24', '24', '23', '21', '20', '19', '18', '18', '18', '18\n'], ['2014/1/3', '豐原', 'AMB_TEMP', '18', '18', '18', '18', '18', '18', '18', '19', '19', '20', '22', '23', '24', '24', '24', '22', '22', '21', '20', '20', '20', '20', '20', '19\n'], ['2014/1/4', '豐原', 'AMB_TEMP', '19', '18', '18', '17', '17', '16', '17', '17', '18', '18', '19', '19', '19', '20', '19', '18', '18', '16', '16', '15', '15', '15', '14', '13\n'], ['2014/1/5', '豐原', 'AMB_TEMP', '13', '12', '13', '12', '12', '12', '12', '13', '14', '16', '18', '19', '20', '21', '21', '20', '19', '17', '16', '16', '15', '14', '14', '13\n'], ['2014/1/6', '豐原', 'AMB_TEMP', '13', '13', '13', '14', '14', '15', '14', '14', '16', '16', '18', '19', '17', 

In [2]:
import numpy as np
vector_row = np.array([1, 2, 3])
print(vector_row)

[1 2 3]


In [3]:
array = np.empty(18).reshape(1,18)

In [4]:
array

array([[ 1.28457068e-322,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  1.35617292e+248, -2.68156159e+154,
        -2.68156159e+154,  8.89318163e-323,  0.00000000e+000]])

In [5]:
array.reshape(18,1)
array

array([[ 1.28457068e-322,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  1.35617292e+248, -2.68156159e+154,
        -2.68156159e+154,  8.89318163e-323,  0.00000000e+000]])

In [6]:
test = np.empty(18)
test

array([ 1.28457068e-322,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  1.35617292e+248, -2.68156159e+154,
       -2.68156159e+154,  8.89318163e-323,  0.00000000e+000])

In [7]:
array = np.null(18).reshape(18,1)
array

AttributeError: module 'numpy' has no attribute 'null'

In [30]:
array = np.array([['AMB_TEMP'], 
                 ['CH4'], 
                 ['CO'], 
                 ['NHMC'], 
                 ['NO'], 
                 ['NO2'], 
                 ['NOx'], 
                 ['O3'], 
                 ['PM10'], 
                 ['PM2.5'], 
                 ['RAINFALL'], 
                 ['RH'], 
                 ['SO2'], 
                 ['THC'], 
                 ['WD_HR'], 
                 ['WIND_DIREC'], 
                 ['WIND_SPEED'], 
                 ['WS_HR']])

with open('train_updated.csv') as f:
    count = 0
    for line in f:
        index = count%18
        if 1==index :
            temp = line.split(',')
            l = len(temp)
            for x in range(3, l) :
                array[index-1][x-3]=temp[x]
            
        count=count+1

print(array[0][1])

IndexError: index 1 is out of bounds for axis 0 with size 1

In [22]:
array = np.array(['AMB_TEMP', 'CH4', 'CO', 'NHMC', 'NO', 'NO2', 'NOx', 'O3', 'PM10', 'PM2.5', 'RAINFALL', 'RH', 'SO2', 'THC', 'WD_HR', 'WIND_DIREC', 'WIND_SPEED', 'WS_HR'])
array.shape
array.reshape(1,18)

array([['AMB_TEMP', 'CH4', 'CO', 'NHMC', 'NO', 'NO2', 'NOx', 'O3',
        'PM10', 'PM2.5', 'RAINFALL', 'RH', 'SO2', 'THC', 'WD_HR',
        'WIND_DIREC', 'WIND_SPEED', 'WS_HR']], dtype='<U10')

In [23]:
array = np.array([['AMB_TEMP'], 
                 ['CH4'], 
                 ['CO'], 
                 ['NHMC'], 
                 ['NO'], 
                 ['NO2'], 
                 ['NOx'], 
                 ['O3'], 
                 ['PM10'], 
                 ['PM2.5'], 
                 ['RAINFALL'], 
                 ['RH'], 
                 ['SO2'], 
                 ['THC'], 
                 ['WD_HR'], 
                 ['WIND_DIREC'], 
                 ['WIND_SPEED'], 
                 ['WS_HR']])
array

array([['AMB_TEMP'],
       ['CH4'],
       ['CO'],
       ['NHMC'],
       ['NO'],
       ['NO2'],
       ['NOx'],
       ['O3'],
       ['PM10'],
       ['PM2.5'],
       ['RAINFALL'],
       ['RH'],
       ['SO2'],
       ['THC'],
       ['WD_HR'],
       ['WIND_DIREC'],
       ['WIND_SPEED'],
       ['WS_HR']], dtype='<U10')

In [24]:
array.shape

(18, 1)

In [25]:
array[0][0]

'AMB_TEMP'

In [26]:
array[1][0]

'CH4'

In [27]:
array[1][1]

IndexError: index 1 is out of bounds for axis 0 with size 1