In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("train_updated.csv", encoding="utf-8", usecols=range(2, 27))
train_data = df.replace(['NR'], [0.0]) 
# train_data is a complete dataset including all observations

In [2]:
train_data

測項     0     1     2     3     4     5     6     7     8  ...  \
0       AMB_TEMP    14    14    14    13    12    12    12    12    15  ...   
1            CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  ...   
2             CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37  0.47  0.78  ...   
3           NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1  0.13  0.26  ...   
4             NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9   2.2   6.6  ...   
5            NO2    16   9.2   8.2   6.9   6.8   3.8   6.9   7.8    15  ...   
6            NOx    17   9.8   8.7   8.6   8.5   5.3   8.8   9.9    22  ...   
7             O3    16    30    27    23    24    28    24    22    21  ...   
8           PM10    56    50    48    35    25    12     4     2    11  ...   
9          PM2.5    26    39    36    35    31    28    25    20    19  ...   
10      RAINFALL     0     0     0     0     0     0     0     0     0  ...   
11            RH    77    68    67    74    72    73    74    73    66  ...   
12           SO2   1.8     2   1.7   1.6   1.9   1.4   1.5   1.6   5.1  ...   
13           THC     2     2     2   1.9   1.9   1.8   1.9   1.9   2.1  ...   
14         WD_HR    37    80    57    76   110   106   101   104   124  ...   
15    WIND_DIREC    35    79   2.4    55    94   116   106    94   232  ...   
16    WIND_SPEED   1.4   1.8     1   0.6   1.7   2.5   2.5     2   0.6  ...   
17         WS_HR   0.5   0.9   0.6   0.3   0.6   1.9     2     2   0.5  ...   
18      AMB_TEMP    16    15    15    14    14    15    16    16    17  ...   
19           CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  ...   
20            CO  0.26  0.25  0.28  0.27  0.24  0.26  0.34  0.56  0.79  ...   
21          NMHC  0.06  0.05  0.06  0.05  0.05  0.07  0.09  0.19  0.31  ...   
22            NO   1.4   1.1   1.3     1   1.2   1.1   1.6   8.4    17  ...   
23           NO2   3.7   3.2   3.3   3.1   3.1   4.3   9.4    19    26  ...   
24           NOx     5   4.3   4.7   4.1   4.3   5.5    11    27    43  ...   
25            O3    39    38    39    39    34    31    30    18    17  ...   
26          PM10    49    34    31    16    18     8    16    24    37  ...   
27         PM2.5    21    23    30    30    22    18    13    13    11  ...   
28      RAINFALL     0     0     0     0     0     0     0     0     0  ...   
29            RH    65    66    70    71    70    67    59    60    55  ...   
...          ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
4290         NOx   8.8   7.5   8.5   8.2   8.6   9.3    18    35    55  ...   
4291          O3    30    33    30    34    37    36    24    13   6.5  ...   
4292        PM10    45    50    64    51    44    34    40    49    44  ...   
4293       PM2.5    14    16    13    14    21    19    23    18    17  ...   
4294    RAINFALL     0     0     0     0     0     0     0     0     0  ...   
4295          RH    71    70    71    70    70    71    69    67    69  ...   
4296         SO2  -0.2     2   2.1   2.2   2.3   2.5   2.8   3.4     5  ...   
4297         THC   1.9   1.9     2   1.9   1.9     2   2.1   2.2   2.3  ...   
4298       WD_HR   115   119   102   119    97    90    97    62    31  ...   
4299  WIND_DIREC   118   119   110   123   111    86   111    29   100  ...   
4300  WIND_SPEED   1.8   1.7   1.8     2   1.6   1.4   0.9   0.8   2.1  ...   
4301       WS_HR   1.5   1.4   1.3   1.9   1.3     1     1   0.6   0.5  ...   
4302    AMB_TEMP    14    14    14    14    14    14    14    14    14  ...   
4303         CH4   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.7  ...   
4304          CO  0.21   0.2  0.17  0.17  0.16  0.14  0.15  0.21   0.2  ...   
4305        NMHC  0.06  0.09  0.05  0.06  0.05  0.04  0.03  0.05  0.09  ...   
4306          NO   1.4   1.6   1.3   0.3   0.3   0.5   0.3   0.8   1.4  ...   
4307         NO2   8.5   8.7   4.1   6.3   4.3     4   4.4   7.3   7.6  ...   
4308         NOx   9.9    10   5.4   6.6   4.6   4.5   4.8   8.1

In [3]:
pm2_5 = train_data[train_data['測項']=='PM2.5'].iloc[:,1:]
# pm2_5 is a subset of complete dataset: only contains PM2.5 observations

In [4]:
pm2_5

0   1   2   3   4   5   6   7   8   9  ...  14  15   16   17   18   19  \
9     26  39  36  35  31  28  25  20  19  30  ...  36  45   42   49   45   44   
27    21  23  30  30  22  18  13  13  11  22  ...  53  43   43   45   46   32   
45    19  25  27  20  16  14  15   8   4   9  ...  32  36   34   45   40   41   
63    27  27  14  20  22  24  26  33  48  50  ...  62  55   56   67   78   83   
81    80  80  76  81  75  66  70  65  66  57  ...  64  73   57   57   53   70   
99    66  55  46  46  46  42  35  35  40  45  ...  62  59   61   50   60   62   
117   41  32  35  31  33  25  36  28  33  29  ...  62  61   47   54   57   59   
135   48  53  60  60  52  47  45  50  43  40  ...  35  36   36   32   33   33   
153   18  15   9   9  14  15  20  16  23  16  ...  20  20   20   18   18   22   
171    6   7   7   0   0   1   1   7   7   8  ...  23  20   18   15   16   10   
189   25  21  25  24  23  18  20  14   7  17  ...  36  36   29   32   33   30   
207   48  56  62  52  40  32  37  31  34  32  ...  19  24   25   14   16   22   
225   10  10  10  13  18  16   7   5   2  11  ...  18  29   38   43   44   48   
243   29  23  21  21  30  26  26  26  23  16  ...  10   6    4    7   14   20   
261    9   4   8   5  14  11  13   4   9  15  ...   4  13   14   18   20   25   
279   24  16   7   7   6   5   2  17  15  33  ...  30  41   38   34   27   26   
297   27  25  22  23  22  22  23  11   2  18  ...  16  20   16   34   32   27   
315   17  26  25  24  10   7  11  16  19   9  ...  81  90  109  109  105  102   
333   64  52  36  41  46  48  38  21  11  11  ...  50  57   66   72   77   72   
351   61  59  60  48  53  60  66  53  55  57  ...  51  47   44   46   46   39   
369   30  32  36  29  16  10  23  27  33  21  ...  21  19   19   19   18   27   
387   22  20  13   8  15  13  22  19  23  15  ...  33  28   25   21   23   27   
405   31  26  17  13  18  29  22  21  23  34  ...  30  32   24   27   17   20   
423   22  27  22  31  32  35  25  14   7   0  ...   8  12   15   17    9   11   
441    6   6   4   4   0   0   0   2   2   2  ...  28  36   23   21   25   16   
459   13  22  29  21  21  14  16   6  11  10  ...  29  29   34   39   40   52   
477   46  44  38  36  23  19   7  21  20  25  ...  24  25   27   24   23   20   
495   32  35  25  13  12   7   7   6   7   9  ...   7  15   12    7    0    3   
513    4   6   0   0   0   7   7   5   7  10  ...  11  12   12    2    6    6   
531    0   0   4   4   8   9  13  10   4   0  ...   3  11    7   15    8   19   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ...  ...  ...  ...   
3789  11   6  14  12  12   0   2   7  12  23  ...  39  32   17   19   27   41   
3807  21  16  26  18  11   6   7  12   4   6  ...  18  30   30   18   11   10   
3825  14  11  14  14  10   4   9  14  10  17  ...  16  26   33   33   37   26   
3843   9   6   6   5   0   4   7   9  12  14  ...   6   3    3   13   19   15   
3861   9   4   6   1   1   0   0   0   4   6  ...  34  54   69   66   59   36   
3879   0   0   0   0   1   1  13  19  23  14  ...  18  18   18   -1   -1   -1   
3897  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  ...  19  19   19   12    3    6   
3915   6  12  11  11   7   3  13  31  47  47  ...  22  22   21   21   19   14   
3933   9   3   0   4   4   8   2   4   8  14  ...  71  69   38    9    9   14   
3951  10   8   8   2   2   0   4  14  25  20  ...  26  26   25   34   39   38   
3969  22  17  17  22  27  26   9   4   0   0  ...   1  18   30   33   15   10   
3987  14   6   0  10  15  24  15  14  14  21  ...  12   4   13   13   17    7   
4005  20   5  12  15  22  14   6   4  13  20  ...  32  38   36   35   27   24   
4023  21  21  21   0   0   0   0   0   0   0  ...   0  10   18   18   18   18   
4041  20  20  20  20  20  21  29  29  27  21  ...  13  11   18   28   33   37   
4059   7   2   0   0   1   5   9   8   2   1  ...  15  16   22   25   27   18   
4077   8   6  19  21  20   4   0   0   0   3  ...  34  35   36   40   31   35   
4095  27  15  11  11  14  15  15  17  

In [5]:
# rearranging train_data
tempxlist = []
tempylist = []
for i in range (15):
    tempx = pm2_5.iloc[:,i:i+9]
    tempx.columns = np.array(range(9))
    tempy = pm2_5.iloc[:,i+9]
    tempy.columns = ['1']
    tempxlist.append(tempx)
    tempylist.append(tempy)

In [6]:
# from all 3600: select first 3200 to train and use the rest 400 to validate

xdata = pd.concat(tempxlist)
xall = np.array(xdata, float)
x = xall[:3200,:]

In [7]:
x.shape

(3200, 9)

In [8]:
ydata = pd.concat(tempylist)
ydata.head()
yall = np.array(ydata, float)
y = yall[:3200]

In [9]:
y.shape

(3200,)

In [10]:
x.shape[0]

3200

In [11]:
bdata = np.ones((x.shape[0],1))  # initial bias = 1

In [12]:
x = np.concatenate((bdata, x), axis=1)
x

array([[ 1., 26., 39., ..., 25., 20., 19.],
       [ 1., 21., 23., ..., 13., 13., 11.],
       [ 1., 19., 25., ..., 15.,  8.,  4.],
       ...,
       [ 1., 24., 23., ..., 19., 23., 21.],
       [ 1., 44., 40., ..., 23., 21., 14.],
       [ 1., 24., 19., ..., 47., 52., 40.]])

In [13]:
x[0]

array([ 1., 26., 39., 36., 35., 31., 28., 25., 20., 19.])

In [14]:
_l = len(x[0])
weights = np.ones((_l))

In [15]:
weights

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [97]:
learn_rate = 1
iteration = 1000
s_grad = np.zeros(_l)

In [98]:
s_grad

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
for i in range (iteration):
    y_prime = np.dot(x, weights)
    loss = y - y_prime
    grad = np.dot(x.transpose(), loss)*(-2)
    s_grad += grad**2
    ada = np.sqrt(s_grad)
    weights = weights - learn_rate*grad/ada

In [100]:
weights # this should be the best b & w set

array([ 2.68622732, -0.14495618,  0.27277639,  0.04154967, -0.41709287,
        0.36816551,  0.2392043 , -0.66814801,  0.27622683,  0.94384464])

In [101]:
# validate the results using the rest 400
x_val = xall[3200:xall.shape[0],:]
x_val.shape

(400, 9)

In [102]:
y_val = yall[3200:yall.shape[0]]
y_val.shape

(400,)

In [103]:
# prep the data to validate
x_val = np.concatenate((np.ones((x_val.shape[0],1)), x_val), axis=1)
x_val

array([[ 1., 41., 36., ..., 10., 13.,  8.],
       [ 1., 28., 31., ...,  4.,  6., 11.],
       [ 1., 60., 57., ..., 23., 28., 20.],
       ...,
       [ 1., 31., 31., ..., 39., 36., 24.],
       [ 1., 21., 21., ..., 11.,  0.,  7.],
       [ 1.,  1.,  7., ..., 28., 17., 24.]])

In [104]:
x_val.shape

(400, 10)

In [105]:
weights

array([ 2.68622732, -0.14495618,  0.27277639,  0.04154967, -0.41709287,
        0.36816551,  0.2392043 , -0.66814801,  0.27622683,  0.94384464])

In [106]:
y_prime = np.dot(x_val, weights)
loss_val = y_val - y_prime
np.average(loss_val) # average loss

-2.085980970718801

In [107]:
# now let's start predicting

testdata = pd.read_csv("given/test_X.csv")

In [108]:
testdata

id_0    AMB_TEMP    15    14  14.1    13  13.1  13.2  13.3  13.4    12
0       id_0         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
1       id_0          CO  0.36  0.35  0.34  0.33  0.33  0.34  0.34  0.37  0.42
2       id_0        NMHC  0.11  0.09  0.09   0.1   0.1   0.1   0.1  0.11  0.12
3       id_0          NO   0.6   0.4   0.3   0.3   0.3   0.7   0.8   0.8   0.9
4       id_0         NO2   9.3   7.1   6.1   5.7   5.5   5.3   5.5   7.1   7.5
5       id_0         NOx   9.9   7.5   6.4   5.9   5.8     6   6.2   7.8   8.4
6       id_0          O3    36    44    45    44    44    44    43    40    38
7       id_0        PM10    51    51    31    40    34    51    42    36    30
8       id_0       PM2.5    27    13    24    29    41    30    29    27    28
9       id_0    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
10      id_0          RH    75    71    71    73    74    74    74    74    74
11      id_0         SO2   1.2   1.2   1.2   1.6   1.5   1.5   1.5   1.6   1.6
12      id_0         THC   1.9   1.8   1.8   1.9   1.9   1.9   1.9   1.9   1.9
13      id_0       WD_HR   116   114   112   109   111   104   107   108   104
14      id_0  WIND_DIREC   115   113   105   102   106   106   112   113   106
15      id_0  WIND_SPEED   2.6   2.2     2   1.9   2.4   2.4   2.5   2.8     2
16      id_0       WS_HR   2.1   2.4   2.2   1.9   2.3   2.3   2.5   2.5   2.3
17      id_1    AMB_TEMP    12    12    12    13    14    15    14    14    13
18      id_1         CH4   1.8   1.8   1.9   1.9   1.8   1.8   1.8   1.8   1.8
19      id_1          CO  0.46  0.58  0.64  0.63  0.58  0.52  0.52  0.51  0.49
20      id_1        NMHC  0.06   0.1  0.12  0.13  0.15  0.12  0.11  0.11  0.14
21      id_1          NO   0.5   0.7   1.5   1.9   1.8   1.7   1.8   1.8   1.8
22      id_1         NO2   5.5   9.4    13    11    10   9.5    10    10    11
23      id_1         NOx     6    10    14    12    12    11    12    12    13
24      id_1          O3    41    34    30    36    38    41    42    42    41
25      id_1        PM10    77    94   116   130   161   177   178   161   150
26      id_1       PM2.5    46    47    57    78    84    76    59    61    61
27      id_1    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
28      id_1          RH    62    60    56    51    48    44    45    45    47
29      id_1         SO2   5.6     6   6.8   7.1   6.4   5.8   5.8   5.9   5.7
...      ...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
4289  id_238         NOx    23    20    17    18    16    11    11   9.7   8.4
4290  id_238          O3    26    24    22    19    20    28    29    33    34
4291  id_238        PM10    70    71    53    45    42    33    33    32    48
4292  id_238       PM2.5    29    27    23    26    24    29    35    35    26
4293  id_238    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
4294  id_238          RH    54    60    67    70    73    73    74    75    75
4295  id_238         SO2   3.5   3.2   2.7   2.8   2.7   2.6   2.2   2.1   1.9
4296  id_238         THC     2     2   1.9     2     2   1.9     2   1.9   1.9
4297  id_238       WD_HR    56    83   116   128   103   115   119   114   101
4298  id_238  WIND_DIREC    63    99   110   141   117   114   127   121    98
4299  id_238  WIND_SPEED   1.1     1   1.8   1.3   1.9   1.9   1.7   2.9   1.8
4300  id_238       WS_HR   0.8   0.8   1.2   1.1   1.3   2.2   1.6   2.1   1.8
4301  id_239    AMB_TEMP    11    11    11    11    11    11    11    13    17
4302  id_239         CH4   1.7   1.7   1.8   1.7   1.7   1.7   1.8   1.7   1.8
4303  id_239          CO  0.32   0.3  0.31  0.24  0.21   0.3  0.97  0.64  1.09
4304  id_239        NMHC  0.08  0.06  0.07  0.05  0.04  0.09  0.35  0.24  0.67
4305  id_239          NO   1.5   1.1     1     1   1.5   2.2    23    12    19
4306  id_239         NO2   5.2   4.9   4.7     4   3.8   6.9    17    14    34
4307  id_239         NOx   6.7     6   5.8     5   5.3   9

In [109]:
pm2_5_test = testdata[testdata['AMB_TEMP']=='PM2.5'].iloc[:,2:]

In [110]:
pm2_5_test

15   14 14.1   13 13.1 13.2 13.3 13.4   12
8      27   13   24   29   41   30   29   27   28
26     46   47   57   78   84   76   59   61   61
44     10   10   25   34   40   39   36   25   22
62     71   58   51   41   41   46   43   34   29
80     13   23   18   10    5    5   13    9   12
98     25   32   40   40   31   27   13   24   29
116    37   42   65   70   71   58   51   41   41
134    17   22   17    9   17   23   29   17   18
152    78   84   76   59   61   61   60   49   49
170    13   13   18   20   14    9   16   22   35
188    27   36   42   32   24   25   32   40   40
206    27   18   24   35   45   51   55   60   62
224    62   59   55   48   62   60   62   54   41
242    44   40   32   24   26   27   18   24   35
260    74   80   73   90   79   67   47   34   28
278    26   34   29   20   24   16   16   13   12
296    28   33   27   37   42   65   70   71   58
314    60   49   49   38   41   30   23   19   20
332    22   20   20   14   12   16   13   16   16
350    30   17   10    5   13   13   13   13   18
368     9    1    4    3    1    4    7   15   14
386    31   24   17    1    9   23   25   29   25
404    54   47   41   39   37   28   28   34   38
422    83   83   85   65   47   30   20   13    7
440    39   57   63   54   45   39   49   55   62
458    14   14    6    4    6   16   31   36   48
476    12   16   24   17    8   11   19   30   29
494    11   19   30   29   26   16   14    9    9
512    17    1    9   23   25   29   25   31   29
530    18   14   14    6    4    6   16   31   36
...   ...  ...  ...  ...  ...  ...  ...  ...  ...
3788   62   34   32   35   36   25   31   30   34
3806   49   66   93  106  111   96   84   79   75
3824   11   11   11   15   20   25   31   26   24
3842  183  159  142  121  137  152  165  154  131
3860    5    1    6   11    9   18   21   35   39
3878   31   43  102  102  136  120  118   94   89
3896   36   25   31   30   34   40   49   66   93
3914   48   60   68   63   71   63   65   62   73
3932   24   14    8    0    4   19   34   42   33
3950   62   73   88   88   70   57   52   44   24
3968   25   37   41   43   49   50   43   40   31
3986   56   72   69   65   71   87   82   74   57
4004   26   32   37   29   27   23   26   24   29
4022    2    0    9   24   44   33   39   29   45
4040   65   64   62   50   45   47   56   57   49
4058   29   16   13    2    0    4    4    9    5
4076   33   39   29   45   27   24   10   10    3
4094   18   20   27   39   41   37   42   56   72
4112   33   29   17   11   13   24   23   27   26
4130    6   10   11   13    5    3    0    0    0
4148   -1   28   41   39   45   39   37   39   39
4166   13    9   15   20   26   23   18   11   14
4184   15   20   26   23   18   11   14   11   22
4202   43   40   31   29   16   13    2    0    4
4220    0    7   16   16   17   17   28   22   17
4238    7   13    6   12    5    6    6   14   21
4256    2    0    4    4    9    5   13    9   15
4274   16   25   12    8    7   11   11    3    0
4292   29   27   23   26   24   29   35   35   26
4310   12    8    7   11   11    3    0    0    0

[240 rows x 9 columns]

In [111]:
x_test = np.array(pm2_5_test, float)
x_test

array([[27., 13., 24., ..., 29., 27., 28.],
       [46., 47., 57., ..., 59., 61., 61.],
       [10., 10., 25., ..., 36., 25., 22.],
       ...,
       [16., 25., 12., ..., 11.,  3.,  0.],
       [29., 27., 23., ..., 35., 35., 26.],
       [12.,  8.,  7., ...,  0.,  0.,  0.]])

In [112]:
# adding bias = 0
x_test_b = np.concatenate((np.ones((x_test.shape[0],1)),x_test),axis=1)

In [113]:
# predicting result
y_star = np.dot(x_test_b, weights)

In [114]:
y_star

array([ 28.00039938,  62.78287746,  18.49452608,  27.36462088,
        11.81572146,  35.95610067,  38.24466707,  17.24484132,
        49.58633767,  32.48226722,  39.22867723,  57.19203142,
        41.42474742,  42.20673324,  28.80451788,  17.94480434,
        51.91444439,  24.57001779,  19.02488678,  21.09480872,
        14.57449231,  28.74665307,  39.98550723,  11.03079939,
        59.54381152,  43.62901915,  27.75784752,  10.45140076,
        26.64744822,  36.7339824 ,  19.66740221,  14.0732773 ,
        17.76135038,   8.21168193,  18.75263395,  38.20966888,
        19.58010132,  29.79158501,   6.30298027,  59.81345865,
        46.09651896,  18.18125789,  52.46643589,  19.24415995,
        38.92626957,  50.32288092,  62.33148933,  41.15117058,
        49.35550359,  44.48790036,  31.1363945 ,  26.1192273 ,
        45.80786714,  26.70171194,  37.94838551,  37.83939452,
        25.14927762,  24.87964231,  32.82590635,  31.73579824,
        16.24500064,  23.56666157,  33.09610443,  54.92

In [115]:
# put the predicted results to the output file
y_pre = pd.read_csv('given/sampleSubmission.csv')

In [116]:
y_pre.value = y_star
y_pre

id       value
0      id_0   28.000399
1      id_1   62.782877
2      id_2   18.494526
3      id_3   27.364621
4      id_4   11.815721
5      id_5   35.956101
6      id_6   38.244667
7      id_7   17.244841
8      id_8   49.586338
9      id_9   32.482267
10    id_10   39.228677
11    id_11   57.192031
12    id_12   41.424747
13    id_13   42.206733
14    id_14   28.804518
15    id_15   17.944804
16    id_16   51.914444
17    id_17   24.570018
18    id_18   19.024887
19    id_19   21.094809
20    id_20   14.574492
21    id_21   28.746653
22    id_22   39.985507
23    id_23   11.030799
24    id_24   59.543812
25    id_25   43.629019
26    id_26   27.757848
27    id_27   10.451401
28    id_28   26.647448
29    id_29   36.733982
..      ...         ...
210  id_210   28.603681
211  id_211   73.554710
212  id_212   20.757901
213  id_213  117.698395
214  id_214   37.961438
215  id_215   81.517619
216  id_216   88.417538
217  id_217   72.450165
218  id_218   29.407457
219  id_219   20.032605
220  id_220   34.501810
221  id_221   56.366790
222  id_222   29.159114
223  id_223   41.278872
224  id_224   44.830279
225  id_225    8.042370
226  id_226    5.570408
227  id_227   69.696408
228  id_228   29.089247
229  id_229    2.137534
230  id_230   44.663564
231  id_231   14.837830
232  id_232   21.161799
233  id_233    7.995900
234  id_234   12.326462
235  id_235   23.416889
236  id_236   13.361440
237  id_237    3.035650
238  id_238   22.554305
239  id_239    3.599224

[240 rows x 2 columns]

In [117]:
y_pre.to_csv('submission.csv')